version: '3.8'

services:
  backend:
    build:
      context: ./../
      dockerfile: ./src/Dockerfile
    container_name: flask-backend
    restart: always
    volumes:
      - ./uploads:/data/uploads
    environment:
      - FLASK_ENV=production
      - MARKDOWN_DIR=/data/uploads
    ports:
      - "5001:5001"

volumes:
  postgres_data:
