version: '3.8'

services:
  backend:
    build:
      context: ./../
      dockerfile: ./src/Dockerfile
    image: iwi-backend:latest
    container_name: flask-backend
    restart: always
    volumes:
      - ./uploads:/data/uploads
    environment:
      - FLASK_ENV=production
      - MARKDOWN_DIR=/data/uploads
      - API_KEY=${API_KEY}
    ports:
      - "5001:5001"
