FROM python:3.10-slim

WORKDIR /app

COPY . .

WORKDIR /app/src

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir -r ./../requirements.txt

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]
