name: Deploy Flask Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1
          rm: false
          debug: true

      - name: Build and start container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.DEPLOY_PATH }}/deploy
            echo "COMPOSE_PROJECT_NAME=iwi-backend" > .env
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            chmod 600 .env

            docker compose down
            docker compose up -d --build
